export const SEARCH_MOVIES = "ACTIONS_MOVIE";

export const START_SEARCH_MOVIES = "START_SEARCH_MOVIES";
export const END_SEARCH_MOVIES = "END_SEARCH_MOVIES";
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
export const SEARCH_MOVIES_FAIL = "SEARCH_MOVIES_FAIL";
